name: Knit R Markdown to HTML

on:
  schedule:
    - cron: '0 1 * * *' # This runs the action daily at 1 AM UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  knit-rmd:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install R packages
      run: |
        R -e "install.packages(c('rmarkdown', 'knitr'), repos='https://cloud.r-project.org/')"

    - name: Knit R Markdown
      run: |
        R -e "rmarkdown::render('index.rmd', output_file = 'index.html')"

    - name: Upload HTML as artifact
      uses: actions/upload-artifact@v3
      with:
        name: index-html
        path: index.html
