name: Knit R Markdown to HTML

on:
  schedule:
    - cron: '0 1 * * *'  # This runs the action daily at 1 AM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  knit-rmd:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Adjust this as needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Updated to the latest version

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev libfreetype6-dev libpng-dev pandoc

      - name: Install R packages
        run: |
          R -e "install.packages(c('rmarkdown', 'knitr', 'DBI', 'RSQLite', 'dplyr', 'kableExtra', 'ggplot2', 'corrplot', 'tidyverse', 'scales', 'viridis'), repos='https://cloud.r-project.org/')"

      - name: Knit R Markdown
        run: |
          R -e "cat('Starting R Markdown rendering...\n'); rmarkdown::render('index.rmd', output_file = 'index.html'); cat('Finished R Markdown rendering.\n')"

      - name: Upload HTML as artifact
        uses: actions/upload-artifact@v3
        with:
          name: index-html
          path: index.html
