name: Knit R Markdown to HTML

on:
  schedule:
    - cron: '0 1 */3 * *'  # Runs every 3 days at 1 AM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  knit-rmd:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Adjust this as needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install and verify system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev libfreetype6-dev libpng-dev pandoc libfontconfig1-dev
          pkg-config --modversion fontconfig freetype2  # Verify the libraries are installed

      - name: Install fonts
        run: sudo apt-get install -y fonts-dejavu-core fonts-liberation

      - name: Set environment variables
        run: |
          export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig
          echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig" >> $GITHUB_ENV

      - name: Set up R environment
        uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        run: |
          R -e "install.packages(c('rmarkdown', 'knitr', 'DBI', 'RSQLite', 'dplyr', 'ggplot2', 'corrplot', 'scales', 'viridis', 'kableExtra', 'tidyverse'), repos='https://cloud.r-project.org/', dependencies=TRUE)"

      - name: Knit R Markdown to HTML
        run: |
          R -e "cat('Starting R Markdown rendering...\n'); rmarkdown::render('index.rmd', output_file = 'index.html'); cat('Finished R Markdown rendering.\n')"

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Commit and Force Push HTML file
        run: |
          git add index.html
          git commit -m "Automated update of index.html" || echo "No changes to commit."
          git push --force  # Forces the push to overwrite the file on the remote branch
